export const TOKENS = {
  USERS_REPOSITORY: Symbol('USERS_REPOSITORY'),
  INSTRUMENTS_REPOSITORY: Symbol('INSTRUMENTS_REPOSITORY'),
  MARKET_CANDLES_REPOSITORY: Symbol('MARKET_CANDLES_REPOSITORY'),
  MARKET_DATA_SYNC_JOBS_REPOSITORY: Symbol('MARKET_DATA_SYNC_JOBS_REPOSITORY'),
  MARKET_DATA_PROVIDERS: Symbol('MARKET_DATA_PROVIDERS'),
  TECHNICAL_ANALYSIS_PROVIDER: Symbol('TECHNICAL_ANALYSIS_PROVIDER'),
  SIGNALS_REPOSITORY: Symbol('SIGNALS_REPOSITORY'),
  STRATEGIES_REPOSITORY: Symbol('STRATEGIES_REPOSITORY'),
  AGENT_DECISIONS_REPOSITORY: Symbol('AGENT_DECISIONS_REPOSITORY'),
  PAPER_TRADES_REPOSITORY: Symbol('PAPER_TRADES_REPOSITORY'),
} as const;
